import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="min-h-screen flex flex-col">
          {/* Navbar */}
          <nav className="bg-gray-800 text-white px-6 py-4 flex justify-between items-center shadow">
            <div className="text-2xl font-bold">
              <Link href="/">Admin Panel</Link>
            </div>
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="hover:underline">
                  Dashboard
                </Link>
              </li>
              <li>
                <Link href="/recipe" className="hover:underline">
                  Recipe
                </Link>
              </li>
              <li>
                <Link href="/user" className="hover:underline">
                  User
                </Link>
              </li>
              <li>
                <Link href="/" className="hover:underline">
                  Settings
                </Link>
              </li>
            </ul>
          </nav>
          {/* Content */}
          <main>
            <Toaster />
            {children}
          </main>
        </div>
  );
}
