import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { Toaster } from "sonner";
import LogoHeader from "@/assets/icons/logo-header.svg";
import LogoFooter from "@/assets/icons/logo-footer.svg";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import SearchBar from "@/components/extension/SearchBar";
import { HiOutlinePhone } from "react-icons/hi";
import { HiOutlineMapPin, HiOutlineSun } from "react-icons/hi2";
import { PiMailboxLight } from "react-icons/pi";
import { FaLinkedin, FaTwitter, FaYoutube, FaInstagram, FaFacebook } from "react-icons/fa6";

export const metadata: Metadata = {
  title: "User Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <nav className=" px-15 py-4 flex justify-between items-center shadow gap-10">
        <div className="text-2xl font-bold">
          <Link href="/">
            <Image src={LogoHeader} alt="Logo" width={192} height={47} />
          </Link>
        </div>
        <SearchBar />
        <div className="flex items-center gap-3">
          <HiOutlineSun className="text-2xl" />
          <Button className="rounded-3xl flex items-center justify-center w-[92px] bg-[#0A4150]">
            Login
          </Button>
        </div>
      </nav>
      {/* Content */}
      <main>
        <Toaster />
        {children}
      </main>

      {/* Footer */}
      <footer>
        <div className="h-[231px] bg-[#0A4150] px-10">
          <div className="w-full py-6 flex justify-between">
            <div className="text-white text-sm space-y-2">
            <Link href="/">
              <Image src={LogoFooter} alt="Logo" width={192} height={47} />
            </Link>
              <p className="flex items-center gap-2">
                <HiOutlineMapPin className="text-2xl" />
                Jl. Gatot Subroto Senayan, Jakarta 10270, Indonesia
              </p>
              <p className="flex items-center gap-2">
                <HiOutlinePhone className="text-2xl" />
                +62 (021) 5730123, 5730106
              </p>
              <p className="flex items-center gap-2">
                <PiMailboxLight className="text-2xl" />
                Apotek @gmail.com
              </p>
            </div>

            <div className="flex flex-col text-sm text-white font-semibold space-y-2">
              <Link href="/" className="hover:text-gray-300 transition font-bold mb-4">Menu</Link>
              <Link href="/" className="hover:text-gray-300 transition">Upload Resep</Link>
              <Link href="/" className="hover:text-gray-300 transition">Bantuan</Link>
              <Link href="/" className="hover:text-gray-300 transition">Kontak Kami</Link>
            </div>
            <div className="flex flex-row gap-4">
              <FaTwitter className="text-2xl text-white" />
              <FaInstagram className="text-2xl text-white" />
              <FaLinkedin className="text-2xl text-white" />
              <FaYoutube className="text-2xl text-white" />
              <FaFacebook className="text-2xl text-white" />
            </div>

          </div>
          <div className="border-t border-white w-full" />
          <p className="text-sm text-white mt-3 flex justify-end">
            CopyRight © Apotek Sejahtera
          </p>
        </div>
      </footer>

    </div>
  );
}
